name = "victory-chatbot"
main = "src/index.ts"
compatibility_date = "2025-09-01"

compatibility_flags = ["nodejs_compat"]

workers_dev = true

[vars]
PINECONE_INDEX_NAME = "rag-systems"
PINECONE_INDEX_HOST = "https://rag-systems-x3bxlpw.svc.aped-4627-b74a.pinecone.io"
NVIDIA_CHAT_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
NVIDIA_EMBEDDING_URL = "https://integrate.api.nvidia.com/v1/embeddings"
CHAT_MODEL = "openai/gpt-oss-20b"